/**
 * Data generator for Graphtrack.
 *  1. Generates a realistic Claude Code session fixture.
 *  2. Parses it into the typed Session model.
 *  3. Builds both candidate graphs (aggregate + chronological) as vis.js data.
 *  4. Writes the result to public/graph-data.js.
 *
 * The page itself (public/index.html) is hand-authored and is NEVER overwritten
 * by this script — regenerating the data must not clobber the app UI.
 *
 * Run: node scripts/build-spike.mjs
 */
import { execSync } from "node:child_process";
import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const FIXTURE = join(ROOT, "test", "fixtures", "session-demo.jsonl");
const OUT_FILE = join(ROOT, "public", "graph-data.js");

// 1. Generate fixture (default size).
execSync(`node "${join(__dirname, "..", "test", "fixtures", "generate-fixture.mjs")}" "${FIXTURE}"`, {
  stdio: "inherit",
});

// 2. Import compiled parser + graph from dist/.
const { parseSession, aggregateTools } = await import("../dist/parser.js");
const { buildAggregateGraph, buildChronologicalGraph, toolColor } = await import("../dist/graph.js");

// 3. Parse.
const session = parseSession(FIXTURE, "my-app");

// Hygiene: attach per-tool token attribution heuristically by spreading each
// turn's total tokens onto its tool calls proportional to call count.
spreadTokens(session);

const aggregate = buildAggregateGraph(session);
const chronological = buildChronologicalGraph(session);
const aggregates = aggregateTools(session).map((a) => ({
  name: a.name,
  calls: a.calls,
  totalTokens: a.totalTokens,
  color: toolColor(a.name),
}));

const data = {
  session: {
    id: session.id,
    project: session.project,
    model: session.model,
    turns: session.turns.length,
    toolCalls: session.turns.reduce((a, t) => a + t.toolCalls.length, 0),
    totalTokens: session.totalTokens,
    totalInput: session.totalInput,
    totalOutput: session.totalOutput,
    totalCacheRead: session.totalCacheRead,
    totalCacheWrite: session.totalCacheWrite,
  },
  aggregate,
  chronological,
  toolAggregates: aggregates,
};

const graphDataJs = `// Generated by scripts/build-spike.mjs — do not edit by hand.\nwindow.GRAPHTRACK_DATA = ${JSON.stringify(data)};\n`;

// 4. Write only the data file. index.html is hand-authored.
mkdirSync(dirname(OUT_FILE), { recursive: true });
writeFileSync(OUT_FILE, graphDataJs);
console.log(`Wrote graph data → ${OUT_FILE}`);
console.log(
  `Session: ${session.turns.length} turns, ${data.session.toolCalls} tool calls, ${data.session.totalTokens} total tokens.`,
);

// --- helpers ---

function spreadTokens(session) {
  for (const turn of session.turns) {
    if (turn.toolCalls.length && turn.totalTokens > 0) {
      const share = turn.totalTokens / turn.toolCalls.length;
      for (const call of turn.toolCalls) {
        call.totalTokens = Math.round(share);
      }
    }
  }
}