/**
 * Phase 0 spike builder.
 *  1. Generates a realistic session fixture.
 *  2. Parses it into the typed Session model.
 *  3. Builds both candidate graphs (aggregate + chronological) with vis.js data.
 *  4. Writes graph-data.js + phase0.html into public/phase0/ so you can open the
 *     page in a browser and judge whether the visualization reads well.
 *
 * Run: node scripts/build-spike.mjs
 */
import { execSync } from "node:child_process";
import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const FIXTURE = join(ROOT, "test", "fixtures", "session-demo.jsonl");

// 1. Generate fixture (default size).
execSync(`node "${join(__dirname, "..", "test", "fixtures", "generate-fixture.mjs")}" "${FIXTURE}"`, {
  stdio: "inherit",
});

// 2. Import compiled parser + graph from dist/.
const { parseSession, aggregateTools } = await import("../dist/parser.js");
const { buildAggregateGraph, buildChronologicalGraph, toolColor } = await import("../dist/graph.js");

// 3. Parse.
const session = parseSession(FIXTURE, "my-app");

// Hygiene: attach per-tool token attribution heuristically by spreading each
// turn's total tokens onto its tool calls proportional to call count.
spreadTokens(session);

const aggregate = buildAggregateGraph(session);
const chronological = buildChronologicalGraph(session);
const aggregates = aggregateTools(session).map((a) => ({
  name: a.name,
  calls: a.calls,
  totalTokens: a.totalTokens,
  color: toolColor(a.name),
}));

const data = {
  session: {
    id: session.id,
    project: session.project,
    model: session.model,
    turns: session.turns.length,
    toolCalls: session.turns.reduce((a, t) => a + t.toolCalls.length, 0),
    totalTokens: session.totalTokens,
    totalInput: session.totalInput,
    totalOutput: session.totalOutput,
    totalCacheRead: session.totalCacheRead,
    totalCacheWrite: session.totalCacheWrite,
  },
  aggregate,
  chronological,
  toolAggregates: aggregates,
};

const graphDataJs = `// Generated by scripts/build-spike.mjs — do not edit by hand.\nwindow.GRAPHTRACK_DATA = ${JSON.stringify(data)};\n`;

const outDir = join(ROOT, "public", "phase0");
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "graph-data.js"), graphDataJs);
writeFileSync(join(outDir, "phase0.html"), html(outDir));
console.log(`Phase 0 spike ready → open ${join(outDir, "phase0.html")} in a browser.`);
console.log(
  `Session: ${session.turns.length} turns, ${data.session.toolCalls} tool calls, ${data.session.totalTokens} total tokens.`,
);

// --- helpers ---

function spreadTokens(session) {
  for (const turn of session.turns) {
    if (turn.toolCalls.length && turn.totalTokens > 0) {
      const share = turn.totalTokens / turn.toolCalls.length;
      for (const call of turn.toolCalls) {
        call.totalTokens = Math.round(share);
      }
    }
  }
}

function html(dir) {
  const rel = (f) => join(dir, f).split(dir)[1].replace(/^[\\/]/, "");
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Graphtrack — Phase 0 spike</title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/vis-network/9.1.9/standalone/umd/vis-network.min.js"></script>
<style>
  :root {
    --canvas:#0a0a0a; --card:#1a1a1a; --yellow:#faff69; --body:#cccccc; --muted:#888888;
  }
  * { box-sizing: border-box; }
  body { margin:0; font-family: Inter, system-ui, sans-serif; background:var(--canvas); color:var(--body); }
  header { padding:16px 24px; border-bottom:1px solid #2a2a2a; display:flex; align-items:center; gap:16px; }
  header h1 { font-size:18px; margin:0; color:#fff; letter-spacing:-0.5px; }
  header span.y { color:var(--yellow); }
  .toggle { margin-left:auto; display:flex; gap:8px; }
  .toggle button {
    background:var(--card); color:var(--body); border:1px solid #3a3a3a;
    padding:6px 12px; border-radius:6px; cursor:pointer; font-size:13px;
  }
  .toggle button.active { background:var(--yellow); color:#0a0a0a; border-color:var(--yellow); font-weight:600; }
  #stats { padding:12px 24px; display:flex; gap:24px; flex-wrap:wrap; font-size:13px; border-bottom:1px solid #2a2a2a; }
  #stats b { color:#fff; }
  #graph { width:100%; height:68vh; }
  footer { padding:12px 24px; font-size:12px; color:var(--muted); }
</style>
</head>
<body>
  <header>
    <h1>Graphtrack <span class="y">▪</span> Phase 0 spike</h1>
    <div class="toggle">
      <button id="btnAgg" class="active">Aggregate (hub &amp; tools)</button>
      <button id="btnChain">Chronological (turns &rarr; tools)</button>
    </div>
  </header>
  <div id="stats">
    <span>Model <b id="sModel">–</b></span>
    <span>Turns <b id="sTurns">–</b></span>
    <span>Tool calls <b id="sCalls">–</b></span>
    <span>Total <b id="sTotal">–</b></span>
    <span>Input <b id="sIn">–</b></span>
    <span>Output <b id="sOut">–</b></span>
    <span>Cache read <b id="sRead">–</b></span>
    <span>Cache write <b id="sWrite">–</b></span>
  </div>
  <div id="graph"></div>
  <footer>Open the same data in a table: see network panel / tool legend below. Data generated locally, nothing uploaded.</footer>
  <script src="graph-data.js"></script>
  <script>
    const D = window.GRAPHTRACK_DATA;
    const $ = (id) => document.getElementById(id);
    const fmt = (n) => n >= 1e6 ? (n/1e6).toFixed(1)+"M" : n >= 1e3 ? (n/1e3).toFixed(1)+"k" : n;

    // Fill stats
    const s = D.session;
    $("sModel").textContent = s.model;
    $("sTurns").textContent = s.turns;
    $("sCalls").textContent = s.toolCalls;
    $("sTotal").textContent = fmt(s.totalTokens);
    $("sIn").textContent = fmt(s.totalInput);
    $("sOut").textContent = fmt(s.totalOutput);
    $("sRead").textContent = fmt(s.totalCacheRead);
    $("sWrite").textContent = fmt(s.totalCacheWrite);

    const container = $("graph");
    const options = {
      physics: { enabled: true, solver: "forceAtlas2Based", stabilization: { iterations: 200 } },
      interaction: { hover: true, tooltipDelay: 200 },
      nodes: { shape: "dot", font: { color: "#cccccc", size: 13 }, widthConstraint: { maximum: 140 } },
      edges: { color: { color: "#3a3a3a", highlight: "#faff69" }, smooth: { enabled: true, type: "dynamic" } },
    };
    let network = null;
    function render(data) {
      if (network) network.destroy();
      network = new vis.Network(container, { nodes: new vis.DataSet(data.nodes), edges: new vis.DataSet(data.edges) }, options);
    }
    render(D.aggregate);
    $("btnAgg").addEventListener("click", () => { setActive("btnAgg"); render(D.aggregate); });
    $("btnChain").addEventListener("click", () => { setActive("btnChain"); render(D.chronological); });
    function setActive(id) { $("btnAgg").classList.toggle("active", id==="btnAgg"); $("btnChain").classList.toggle("active", id==="btnChain"); }
  </script>
</body>
</html>
`;
}